repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.9
      - id: black-jupyter
        language_version: python3.9
  - repo: local
    hooks:
      - id: my-nb-clean
        name: custom-nb-clean
        entry: python scripts/my-nb-clean.py
        language: system
        files: '.*\.ipynb'
